# Generated by Django 6.0.2 on 2026-03-05 13:48

import core.utils
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('days', models.PositiveIntegerField(default=2, verbose_name='Jours offerts')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, verbose_name='Order Id')),
                ('platform', models.CharField(choices=core.utils.platform_choices, max_length=128, verbose_name='Plateforme')),
                ('price', models.PositiveIntegerField(verbose_name='Prix')),
                ('duration', models.CharField(max_length=8, verbose_name='Durée')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('status', models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('pending_validation', 'En attente de validation'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending_payment', max_length=50, verbose_name='Statut')),
                ('type', models.CharField(choices=[('mutual', 'Mutualisé'), ('personal', 'Personnel'), ('trial', 'Essai')], default='mutual', max_length=100)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=payments.models.payment_proof_path, verbose_name="Capture d'écran")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('validated', models.BooleanField(default=False, verbose_name='Validé')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('rejected', models.BooleanField(default=False, verbose_name='Refusé')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du refus')),
            ],
            options={
                'verbose_name': 'Preuve de paiement',
                'verbose_name_plural': 'Preuves de paiement',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name="Date d'expiration")),
                ('status', models.CharField(default='active', max_length=10, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
    ]
