# Generated by Django 6.0.2 on 2026-07-28 14:50

import core.utils
import django.db.models.deletion
import django.utils.timezone
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=10, verbose_name='Opérateur')),
                ('number', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du propriétaire')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Numéro de Paiement',
                'verbose_name_plural': 'Numéros de Paiement',
                'ordering': ['provider', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=payments.models.payment_proof_path, verbose_name="Capture d'écran")),
                ('image2', models.ImageField(blank=True, null=True, upload_to=payments.models.payment_proof_path, verbose_name="Capture d'écran 2 (optionnel)")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('validated', models.BooleanField(default=False, verbose_name='Validé')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('rejected', models.BooleanField(default=False, verbose_name='Refusé')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du refus')),
            ],
            options={
                'verbose_name': 'Preuve de paiement',
                'verbose_name_plural': 'Preuves de paiement',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name="Date d'expiration")),
                ('status', models.CharField(default='active', max_length=10, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('color', models.CharField(default='#ffffff', max_length=20, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Marqueur',
                'verbose_name_plural': 'Marqueurs',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_number', models.CharField(max_length=128, verbose_name='Numéro du profil')),
                ('profile_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Code PIN du profil')),
                ('account_number', models.CharField(blank=True, default='', max_length=128, verbose_name='Numéro du compte')),
                ('platform', models.CharField(blank=True, default='', max_length=255, verbose_name='Plateforme')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Lié le')),
                ('unlinked_at', models.DateTimeField(auto_now_add=True, verbose_name='Délié le')),
            ],
            options={
                'verbose_name': 'Historique de profil',
                'verbose_name_plural': 'Historiques de profils',
                'ordering': ['-unlinked_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('days', models.PositiveIntegerField(default=2, verbose_name='Jours offerts')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('status', models.BooleanField(default=True, verbose_name='Actif')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text="Nombre maximum d'utilisations (0 pour illimité)", verbose_name="Limite d'utilisation")),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de fois utilisé')),
                ('platform', models.ForeignKey(blank=True, help_text='Laisser vide pour un code valable sur toutes les plateformes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_codes', to='core.platform', verbose_name='Plateforme')),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, verbose_name='Order Id')),
                ('platform', models.CharField(choices=core.utils.platform_choices, max_length=128, verbose_name='Plateforme')),
                ('price', models.PositiveIntegerField(verbose_name='Prix')),
                ('duration', models.CharField(max_length=8, verbose_name='Durée')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'achat")),
                ('status', models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('pending_validation', 'En attente de validation'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending_payment', max_length=50, verbose_name='Statut')),
                ('motif', models.CharField(choices=[('subscription', 'Abonnement'), ('renewal', 'Renouvellement'), ('extension', 'Prolongement')], default='subscription', max_length=20, verbose_name='Motif')),
                ('type', models.CharField(choices=[('mutual', 'Mutualisé'), ('personal', 'Personnel')], default='mutual', max_length=100)),
                ('gift_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.giftcode', verbose_name='Code Promo utilisé')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
