# Generated by Django 6.0.2 on 2026-07-28 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='payments.order'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_proofs', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.order'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='products.profile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='renewal_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='payments.subscription', verbose_name='Renouvellement de'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history', to='payments.subscription', verbose_name='Abonnement lié'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='markers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='payments.subscriptionmarker', verbose_name='Marqueurs'),
        ),
        migrations.AddField(
            model_name='subscriptionprofilehistory',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_history', to='payments.subscription', verbose_name='Abonnement'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['validated', 'rejected', '-submitted_at'], name='proof_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'purchase_date'], name='order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-purchase_date'], name='order_purchase_date_desc'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform', 'status'], name='order_platform_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expiration_date'], name='sub_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='sub_user_status_idx'),
        ),
    ]
