# Generated by Django 6.0.2 on 2026-08-11 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('products', '0004_encrypt_account_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notified_j',
            field=models.BooleanField(default=False, verbose_name='Notif J envoyée'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notified_j1',
            field=models.BooleanField(default=False, verbose_name='Notif J+1 envoyée'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notified_j3',
            field=models.BooleanField(default=False, verbose_name='Notif J-3 envoyée'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'notified_j3', 'expiration_date'], name='sub_notify_j3_idx'),
        ),
    ]
