# Generated by Django 6.0.2 on 2026-03-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_price_tiers'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='platform',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un code valable sur toutes les plateformes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_codes', to='core.platform', verbose_name='Plateforme'),
        ),
    ]
