# Generated by Django 6.0.2 on 2026-03-12 18:54

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_platform_to_giftcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=payments.models.payment_proof_path, verbose_name="Capture d'écran 2 (optionnel)"),
        ),
    ]
