# Generated by Django 6.0.2 on 2026-03-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text="Nombre maximum d'utilisations (0 pour illimité)", verbose_name="Limite d'utilisation"),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de fois utilisé'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.giftcode', verbose_name='Code Promo utilisé'),
        ),
    ]
