# Generated by Django 6.0.2 on 2026-04-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_subscription_order_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history', to='payments.subscription', verbose_name='Abonnement lié'),
        ),
    ]
