# Generated by Django 6.0.2 on 2026-04-20 15:12

from django.db import migrations


def populate_order_subscriptions(apps, schema_editor):
    Order = apps.get_model('payments', 'Order')
    Subscription = apps.get_model('payments', 'Subscription')

    # 1. Link orders that are currently the "main" order of a subscription
    for sub in Subscription.objects.all():
        if sub.order:
            sub.order.subscription = sub
            sub.order.save()

    # 2. Link orders that are renewals of a subscription
    for order in Order.objects.filter(renewal_from__isnull=False):
        order.subscription = order.renewal_from
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_order_subscription'),
    ]

    operations = [
        migrations.RunPython(populate_order_subscriptions),
    ]
