# Generated by Django 6.0.2 on 2026-04-20 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20260420_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'achat"),
        ),
    ]
