# Generated by Django 6.0.2 on 2026-05-11 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_order_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_number', models.CharField(max_length=128, verbose_name='Numéro du profil')),
                ('profile_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Code PIN du profil')),
                ('account_number', models.CharField(blank=True, default='', max_length=128, verbose_name='Numéro du compte')),
                ('platform', models.CharField(blank=True, default='', max_length=255, verbose_name='Plateforme')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Lié le')),
                ('unlinked_at', models.DateTimeField(auto_now_add=True, verbose_name='Délié le')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_history', to='payments.subscription', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': 'Historique de profil',
                'verbose_name_plural': 'Historiques de profils',
                'ordering': ['-unlinked_at'],
            },
        ),
    ]
