# Generated by Django 6.0.2 on 2026-05-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_add_subscription_profile_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('color', models.CharField(default='#ffffff', max_length=20, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Marqueur',
                'verbose_name_plural': 'Marqueurs',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='motif',
            field=models.CharField(choices=[('subscription', 'Abonnement'), ('renewal', 'Renouvellement'), ('extension', 'Prolongement')], default='subscription', max_length=20, verbose_name='Motif'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionmarker', verbose_name='Marqueur'),
        ),
    ]
