# Generated by Django 6.0.2 on 2026-06-09 01:07

from django.db import migrations, models

def copy_markers_data(apps, schema_editor):
    Subscription = apps.get_model('payments', 'Subscription')
    for sub in Subscription.objects.exclude(marker__isnull=True):
        sub.markers.add(sub.marker)

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_subscriptionmarker_order_motif_subscription_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='markers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='payments.subscriptionmarker', verbose_name='Marqueurs'),
        ),
        migrations.RunPython(copy_markers_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscription',
            name='marker',
        ),
    ]
