# Generated by Django 6.0.2 on 2026-06-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_remove_subscription_marker_subscription_markers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=10, verbose_name='Opérateur')),
                ('number', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du propriétaire')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Numéro de Paiement',
                'verbose_name_plural': 'Numéros de Paiement',
                'ordering': ['provider', '-created_at'],
            },
        ),
    ]
