# Generated by Django 6.0.2 on 2026-07-21 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_paymentnumber'),
        ('products', '0008_account_account_status_end_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'purchase_date'], name='order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-purchase_date'], name='order_purchase_date_desc'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['platform', 'status'], name='order_platform_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['validated', 'rejected', '-submitted_at'], name='proof_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expiration_date'], name='sub_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='sub_user_status_idx'),
        ),
    ]
