# Generated by Django 6.0.2 on 2026-07-28 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('country_code', models.CharField(max_length=5, verbose_name='Indicatif')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total des commandes')),
                ('total_subscriptions', models.PositiveIntegerField(default=0, verbose_name='Total des abonnements')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('twofa_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('twofa_method', models.CharField(choices=[('totp', 'TOTP'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='totp', max_length=10, verbose_name='Méthode 2FA')),
                ('twofa_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='Secret 2FA')),
                ('twofa_recovery_codes', models.JSONField(blank=True, default=list, verbose_name='Codes de récupération')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='TwoFACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('method', models.CharField(choices=[('totp', 'TOTP'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Méthode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expiration')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code 2FA',
                'verbose_name_plural': 'Codes 2FA',
                'indexes': [models.Index(fields=['user', 'verified'], name='users_twofa_user_id_3daf75_idx'), models.Index(fields=['expires_at'], name='users_twofa_expires_10ddea_idx')],
            },
        ),
    ]
