# Generated by Django 6.0.2 on 2026-08-10 17:15

import core.fields
from django.db import migrations


def encrypt_existing_twofa_secrets(apps, schema_editor):
    """Re-save existing User rows so plain-text twofa_secret becomes encrypted.

    EncryptedCharField.get_prep_value transparently encrypts values that don't
    already decrypt, so a plain .save() is enough. Rows with empty/blank
    secrets are skipped.
    """
    User = apps.get_model('users', 'User')
    for user in User.objects.exclude(twofa_secret=''):
        # Will trigger encryption on save because the existing value is plain-text
        user.save(update_fields=['twofa_secret'])


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twofa_secret',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255, verbose_name='Secret 2FA'),
        ),
        migrations.RunPython(encrypt_existing_twofa_secrets, reverse_migration),
    ]
