# Generated by Django 6.0.2 on 2026-03-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_trial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_optin',
            field=models.BooleanField(default=False, verbose_name='Opt-in WhatsApp'),
        ),
    ]
