# Generated by Django 6.0.2 on 2026-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_whatsapp_optin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_optin',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
