# Generated by Django 6.0.2 on 2026-07-27 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_whatsapp_optin_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA activé'),
        ),
        migrations.AddField(
            model_name='user',
            name='twofa_method',
            field=models.CharField(choices=[('totp', 'TOTP'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='totp', max_length=10, verbose_name='Méthode 2FA'),
        ),
        migrations.AddField(
            model_name='user',
            name='twofa_recovery_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Codes de récupération'),
        ),
        migrations.AddField(
            model_name='user',
            name='twofa_secret',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Secret 2FA'),
        ),
        migrations.CreateModel(
            name='TwoFACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code')),
                ('method', models.CharField(choices=[('totp', 'TOTP'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Méthode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expiration')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code 2FA',
                'verbose_name_plural': 'Codes 2FA',
                'indexes': [models.Index(fields=['user', 'verified'], name='users_twofa_user_id_3daf75_idx'), models.Index(fields=['expires_at'], name='users_twofa_expires_10ddea_idx')],
            },
        ),
    ]
