# Generated by Django 6.0.2 on 2026-07-28 14:50

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Plateforme')),
                ('sub', models.CharField(blank=True, max_length=125, verbose_name='Detail')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=core.models.poster_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=core.models.video_upload_path)),
                ('has_personal', models.BooleanField(default=False, verbose_name='Offre personnelle disponible')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Plateforme',
                'verbose_name_plural': 'Plateformes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name="Nombre d'étoiles")),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Depuis')),
            ],
            options={
                'verbose_name': 'Avi',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('mutual', 'Mutualisé'), ('personal', 'Personnel')], default='mutual', max_length=20, verbose_name='Type')),
                ('category', models.CharField(blank=True, default='', help_text='Sous-catégorie (ex: Mobile, Essentiel, Premium pour Netflix personnel). Laisser vide sinon.', max_length=50, verbose_name='Catégorie')),
                ('base_price', models.PositiveIntegerField(help_text='Tous les autres prix sont calculés automatiquement à partir de ce prix.', verbose_name='Prix de base (1 mois)')),
                ('category_description', models.CharField(blank=True, default='', help_text="Ex: '1 écran, qualité 480p'", max_length=100, verbose_name='Description catégorie')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='core.platform', verbose_name='Plateforme')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'ordering': ['account_type', 'base_price'],
            },
        ),
    ]
