# Generated by Django 6.0.2 on 2026-03-05 13:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Plateforme')),
                ('sub', models.CharField(blank=True, max_length=125, verbose_name='Detail')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=core.models.poster_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=core.models.video_upload_path)),
                ('plan', models.JSONField(default=dict, verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plateforme',
                'verbose_name_plural': 'Plateformes',
                'ordering': ['plan'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name="Nombre d'étoiles")),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Depuis')),
            ],
            options={
                'verbose_name': 'Avi',
                'verbose_name_plural': 'Avis',
            },
        ),
    ]
