# Generated by Django 6.0.2 on 2026-07-28 14:54

from django.db import migrations


PLATFORMS = [
    # name, order, has_personal, color
    ('Disney+',       0,  False, '#A855F7'),
    ('Paramount+',    1,  False, '#7DD3FC'),
    ('Apple TV',      2,  False, '#000000'),
    ('HBO Max',       3,  True,  '#9CA3AF'),
    ('Netflix',       4,  True,  '#EF4444'),
    ('Prime Video',   5,  True,  '#3B82F6'),
    ('Crunchyroll',   6,  True,  '#F97316'),
    ('Spotify',       7,  True,  '#22C55E'),
    ('Apple Music',   8,  True,  '#F472B6'),
    ('Surfshark',     9,  True,  '#7DD3FC'),
    ('Onoff',         10, False, '#3B82F6'),
]

PRICE_TIERS = [
    # platform, type, category, base_price, description
    ('Netflix',       'mutual',   '',         2500,  ''),
    ('Disney+',       'mutual',   '',         2500,  ''),
    ('HBO Max',       'mutual',   '',         2500,  ''),
    ('Paramount+',    'mutual',   '',         2500,  ''),
    ('Prime Video',   'mutual',   '',         2000,  ''),
    ('Spotify',       'mutual',   '',         2000,  ''),
    ('Apple Music',   'mutual',   '',         2000,  ''),
    ('Crunchyroll',   'mutual',   '',         1500,  ''),
    ('Surfshark',     'mutual',   '',         1500,  ''),
    ('Netflix',       'personal', 'Mobile',    4500, '1 écran, qualité 480p'),
    ('Netflix',       'personal', 'Essentiel', 5500, '1 écran, qualité 1080p'),
    ('Netflix',       'personal', 'Premium',  10500, '4 écrans, qualité 4K'),
    ('Prime Video',   'personal', '',         8000,  ''),
    ('Crunchyroll',   'personal', '',         5000,  ''),
    ('Apple Music',   'personal', '',         5000,  ''),
    ('Spotify',       'personal', '',         5000,  ''),
    ('Surfshark',     'personal', '',         5000,  ''),
    ('HBO Max',       'personal', '',         7500,  ''),
]


def seed(apps, schema_editor):
    Platform = apps.get_model('core', 'Platform')
    PriceTier = apps.get_model('core', 'PriceTier')

    for name, order, has_personal, color in PLATFORMS:
        Platform.objects.get_or_create(
            name=name,
            defaults={'order': order, 'has_personal': has_personal, 'color': color},
        )

    for platform_name, account_type, category, base_price, description in PRICE_TIERS:
        platform = Platform.objects.filter(name=platform_name).first()
        if not platform:
            continue
        PriceTier.objects.get_or_create(
            platform=platform,
            account_type=account_type,
            category=category,
            defaults={
                'base_price': base_price,
                'category_description': description,
            },
        )


def reverse(apps, schema_editor):
    PriceTier = apps.get_model('core', 'PriceTier')
    Platform = apps.get_model('core', 'Platform')
    PriceTier.objects.all().delete()
    Platform.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed, reverse),
    ]
