# Generated by Django 6.0.2 on 2026-07-28 14:54

from django.db import migrations


PLATFORMS = [
    # name, order, has_personal
    ('Netflix',       0,  True),
    ('Disney Plus',   1,  False),
    ('HBO Max',       2,  True),
    ('Paramount+',    3,  False),
    ('Prime Video',   4,  True),
    ('Spotify',       5,  True),
    ('Apple Music',   6,  True),
    ('Crunchyroll',   7,  True),
    ('Surfshark',     8,  True),
]

PRICE_TIERS = [
    # platform, type, category, base_price, description
    ('Netflix',       'mutual',   '',         2500,  ''),
    ('Disney Plus',   'mutual',   '',         2500,  ''),
    ('HBO Max',       'mutual',   '',         2500,  ''),
    ('Paramount+',    'mutual',   '',         2500,  ''),
    ('Prime Video',   'mutual',   '',         2000,  ''),
    ('Spotify',       'mutual',   '',         2000,  ''),
    ('Apple Music',   'mutual',   '',         2000,  ''),
    ('Crunchyroll',   'mutual',   '',         1500,  ''),
    ('Surfshark',     'mutual',   '',         1500,  ''),
    ('Netflix',       'personal', 'Mobile',    4500, '1 écran, qualité 480p'),
    ('Netflix',       'personal', 'Essentiel', 5500, '1 écran, qualité 1080p'),
    ('Netflix',       'personal', 'Premium',  10500, '4 écrans, qualité 4K'),
    ('Prime Video',   'personal', '',         8000,  ''),
    ('Crunchyroll',   'personal', '',         5000,  ''),
    ('Apple Music',   'personal', '',         5000,  ''),
    ('Spotify',       'personal', '',         5000,  ''),
    ('Surfshark',     'personal', '',         5000,  ''),
    ('HBO Max',       'personal', '',         7500,  ''),
]


def seed(apps, schema_editor):
    Platform = apps.get_model('core', 'Platform')
    PriceTier = apps.get_model('core', 'PriceTier')

    for name, order, has_personal in PLATFORMS:
        Platform.objects.get_or_create(
            name=name,
            defaults={'order': order, 'has_personal': has_personal},
        )

    for platform_name, account_type, category, base_price, description in PRICE_TIERS:
        platform = Platform.objects.filter(name=platform_name).first()
        if not platform:
            continue
        PriceTier.objects.get_or_create(
            platform=platform,
            account_type=account_type,
            category=category,
            defaults={
                'base_price': base_price,
                'category_description': description,
            },
        )


def reverse(apps, schema_editor):
    PriceTier = apps.get_model('core', 'PriceTier')
    Platform = apps.get_model('core', 'Platform')
    PriceTier.objects.all().delete()
    Platform.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed, reverse),
    ]
