# Generated by Django 6.0.2 on 2026-03-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Plateforme', 'verbose_name_plural': 'Plateformes'},
        ),
        migrations.RemoveField(
            model_name='platform',
            name='plan',
        ),
        migrations.AddField(
            model_name='platform',
            name='has_personal',
            field=models.BooleanField(default=False, verbose_name='Offre personnelle disponible'),
        ),
        migrations.AddField(
            model_name='platform',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Plateforme'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('mutual', 'Mutualisé'), ('personal', 'Personnel')], default='mutual', max_length=20, verbose_name='Type')),
                ('category', models.CharField(blank=True, default='', help_text='Sous-catégorie (ex: Mobile, Essentiel, Premium pour Netflix personnel). Laisser vide sinon.', max_length=50, verbose_name='Catégorie')),
                ('base_price', models.PositiveIntegerField(help_text='Tous les autres prix sont calculés automatiquement à partir de ce prix.', verbose_name='Prix de base (1 mois)')),
                ('category_description', models.CharField(blank=True, default='', help_text="Ex: '1 écran, qualité 480p'", max_length=100, verbose_name='Description catégorie')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='core.platform', verbose_name='Plateforme')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'ordering': ['account_type', 'base_price'],
                'unique_together': {('platform', 'account_type', 'category')},
            },
        ),
    ]
