# Generated by Django 6.0.2 on 2026-08-01 03:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.logo_upload_path, validators=[core.models.validate_logo_image], verbose_name='Logo'),
        ),
    ]
