# Generated by Django 6.0.2 on 2026-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Type')),
                ('chanel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=64, verbose_name="Canal d'envoie")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('quewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Type')),
                ('chanel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=64, verbose_name="Canal d'envoie")),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('quewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
