# Generated by Django 6.0.2 on 2026-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chanel',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=64, verbose_name="Canal d'envoie"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='chanel',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=64, verbose_name="Canal d'envoie"),
        ),
    ]
