"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Sentry — initialised before anything else so it can capture boot errors.
SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv('ENVIRONMENT', 'development'),
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- Environment ---
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')
if ENVIRONMENT not in ('development', 'staging', 'production'):
    raise RuntimeError(f"ENVIRONMENT must be one of: development, staging, production — got '{ENVIRONMENT}'")

IS_PRODUCTION = ENVIRONMENT == 'production'

# --- Secrets ---
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-please-change-me-in-dev-only')
FERNET_KEY = os.getenv('FERNET_KEY', '').strip() or None

if IS_PRODUCTION:
    if not os.getenv('SECRET_KEY') or len(SECRET_KEY) < 50:
        raise RuntimeError('SECRET_KEY must be set and at least 50 characters in production.')
    if not FERNET_KEY:
        raise RuntimeError('FERNET_KEY must be set in production — field-level encryption depends on it.')

# --- Debug ---
DEBUG = os.getenv('DEBUG', 'false').lower() == 'true'
if IS_PRODUCTION and DEBUG:
    raise RuntimeError('DEBUG must not be True in production.')

# --- Hosts ---
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:3001,http://localhost:3002',
    ).split(',') if o.strip()
]

# --- CORS ---
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3001,http://localhost:3002',
    ).split(',') if o.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type',
    'user-agent', 'x-csrftoken', 'x-requested-with',
]
CORS_EXPOSE_HEADERS = ['Content-Type']

# --- Production security headers ---
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # third party
    'corsheaders',
    'storages',
    'whitenoise.runserver_nostatic',
    'django_celery_beat',
    'django_celery_results',
    'anymail',
    'rest_framework',
    'rest_framework_simplejwt',
    'djoser',
    'drf_spectacular',
    # local
    'payments.apps.PaymentsConfig',
    'users.apps.UsersConfig',
    'products.apps.ProductsConfig',
    'core.apps.CoreConfig',
    'dashboard.apps.DashboardConfig',
    'notifications.apps.NotificationsConfig',
    'api.apps.ApiConfig',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django_structlog.middlewares.RequestMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if IS_PRODUCTION:
    DATABASES['default'] = dj_database_url.parse(
        os.getenv('DATABASE_URL')
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Redirection
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'core:landing'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# aws credentials
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
AWS_ENDPOINT_URL = os.getenv('AWS_ENDPOINT_URL')

# Static files and media files with S3
STORAGES = {
    # C'est la configuration pour les fichiers média
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
        },
    },

    # C'est la configuration pour les fichiers statiques
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        "OPTIONS": {
        },
    }
}

# Others S3 parameters
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_EXPIRE = 3600


# Celery Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
DJANGO_CELERY_BEAT_TZ_AWARE = True
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
RESULT_BACKEND = 'django-db'

# Limites de temps pour éviter les tâches zombies (hard / soft)
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60


# Cache Configuration (for distributed locking)
# Falls back to local memory cache when REDIS_URL is not set or unreachable,
# so DRF throttling works without a Redis instance in dev.
REDIS_URL = os.getenv('REDIS_URL', '').strip()
CACHE_BACKEND_OVERRIDE = os.getenv('CACHE_BACKEND', '').strip().lower()

if REDIS_URL and CACHE_BACKEND_OVERRIDE != 'locmem':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'db': 0,
                'socket_timeout': 2,
                'socket_connect_timeout': 2,
            },
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'streampartner-dev-cache',
        }
    }

# drf-spectacular — OpenAPI schema
SPECTACULAR_SETTINGS = {
    'TITLE': 'StreamPartner API',
    'DESCRIPTION': 'REST API for StreamPartner — subscriptions, payments, admin.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# django-structlog: structured request logging (JSON in prod, console in dev)
# https://django-structlog.readthedocs.io/
import structlog

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.JSONRenderer() if IS_PRODUCTION else structlog.dev.ConsoleRenderer(),
    ],
    wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
    context_class=dict,
    logger_factory=structlog.PrintLoggerFactory(),
    cache_logger_on_first_use=True,
)

# Enable Celery logging via structlog if Celery is loaded
DJANGO_STRUCTLOG_CELERY_ENABLED = True

# Mobile Money fallback numbers (used only if no active PaymentNumber in DB)
MOBILE_MONEY_MTN = {
    'number': os.getenv('MOBILE_MONEY_MTN_NUMBER', ''),
    'name': os.getenv('MOBILE_MONEY_MTN_NAME', 'Stream Partner'),
}
MOBILE_MONEY_ORANGE = {
    'number': os.getenv('MOBILE_MONEY_ORANGE_NUMBER', ''),
    'name': os.getenv('MOBILE_MONEY_ORANGE_NAME', 'Stream Partner'),
}

# Email configuration
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY"),
}
DEFAULT_FROM_EMAIL = "Stream Partner <hello@contact.streampartner.in>"
# Frontend base URL (used for admin-generated links: password reset, etc.)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://streampartner.in')
# Report System Configuration
REPORT_RECIPIENT_EMAIL = os.getenv('REPORT_RECIPIENT_EMAIL', 'streampartnernotif@gmail.com')
REPORT_PERIOD_DAYS = int(os.getenv('REPORT_PERIOD_DAYS', '7'))

# Subscription Notification Email
SUBSCRIPTION_NOTIFICATION_EMAIL = os.getenv('SUBSCRIPTION_NOTIFICATION_EMAIL', 'streampartnernotif@gmail.com')

# 2FA — WhatsApp OTP via Whatomate
WHATOMATE_BASE_URL = os.getenv('WHATOMATE_BASE_URL', 'https://wapi.streampartner.in')
WHATOMATE_API_KEY = os.getenv('WHATOMATE_API_KEY', '')
WHATOMATE_TEMPLATE_NAME = os.getenv('WHATOMATE_TEMPLATE_NAME', 'otp')

import logging
if not WHATOMATE_API_KEY:
    logging.getLogger(__name__).warning(
        "WHATOMATE_API_KEY is not configured — WhatsApp 2FA OTP will not work."
    )


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.cookie_auth.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '120/min',
        'login': '5/min',
        'otp': '3/min',
        'register': '5/min',
    },
}

# JWT lifetime (access short, refresh long). Tunable via env.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '60'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('JWT',),
}

# Djoser: phone-based authentication (custom User model)
DJOSER = {
    'LOGIN_FIELD': 'phone_number',
    'USER_CREATE_PASSWORD_ENTER_RETYPE': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': False,
    'SEND_CONFIRMATION_EMAIL': False,
    'SERIALIZERS': {
        'user': 'api.serializers.auth.UserSerializer',
        'current_user': 'api.serializers.auth.UserSerializer',
        'user_create': 'api.serializers.auth.UserCreateSerializer',
        'password_reset': 'api.serializers.auth.PasswordResetSerializer',
    },
    'EMAIL': {
        'password_reset': 'api.serializers.auth.NoopPasswordResetEmail',
    },
    'PERMISSIONS': {
        'user': ['rest_framework.permissions.IsAuthenticated'],
        'user_list': ['rest_framework.permissions.IsAdminUser'],
    },
}


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO' if IS_PRODUCTION else 'DEBUG',
        },
        'django_structlog': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'payments': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'notifications': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'products': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'dashboard': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    },
}


