# Generated by Django 6.0.2 on 2026-07-16 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token Expo')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='android', max_length=10, verbose_name='Plateforme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token Push',
                'verbose_name_plural': 'Tokens Push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données (deep linking)')),
                ('notification_type', models.CharField(choices=[('order', 'Commande'), ('subscription', 'Abonnement'), ('payment', 'Paiement'), ('user', 'Utilisateur'), ('system', 'Système')], default='system', max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification Push',
                'verbose_name_plural': 'Notifications Push',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_9a0395_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_0b27ea_idx')],
            },
        ),
    ]
