# Generated by Django 6.0.2 on 2026-07-28 14:50

import core.utils
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('color', models.CharField(default='#ffffff', max_length=20, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Marqueur',
                'verbose_name_plural': 'Marqueurs',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', products.models.EncryptedCharField(max_length=255, verbose_name='Numéro')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la carte')),
                ('cvv', models.CharField(max_length=10, verbose_name='CVV')),
                ('telephone', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('expiration_date', models.DateField(verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cartes',
                'ordering': ['expiration_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Numéro')),
                ('platform', models.CharField(choices=core.utils.platform_choices, max_length=255, verbose_name='Plateforme')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('profiles', models.PositiveIntegerField(default=0, verbose_name='N° Profile')),
                ('max_profile', models.PositiveIntegerField(default=5, verbose_name='Profile maximum')),
                ('type', models.CharField(choices=[('mutual', 'Mutualisé'), ('personal', 'Personnel')], default='mutual', max_length=100)),
                ('place', models.PositiveIntegerField(default=2, help_text="Nombre maximum d'abonnements pouvant être liés à ce compte", verbose_name='Places disponibles')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('month_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de mois')),
                ('remaining_day', models.PositiveIntegerField(default=0, verbose_name='Jours restants')),
                ('status', models.CharField(choices=[('activate', 'Activé'), ('desactivate', 'Désactivé')], default='activate', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('markers', models.ManyToManyField(blank=True, related_name='accounts', to='products.accountmarker', verbose_name='Marqueurs')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.card', verbose_name='Carte')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['-remaining_day'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, verbose_name='Numéro')),
                ('code', models.CharField(max_length=128, verbose_name='Code')),
                ('place', models.PositiveIntegerField(choices=[(1, 'Place 1'), (2, 'Place 2')], default=1, help_text='Numéro de place (1 ou 2)', verbose_name='Place')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.account', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status', 'end_date'], name='account_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['platform', 'status'], name='account_platform_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('number', 'platform'), name='unique_account_number_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('email', 'platform'), name='unique_account_email_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('number', 'account'), name='unique_profile_number_per_account'),
        ),
    ]
