# Generated by Django 6.0.2 on 2026-03-05 13:48

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Numéro')),
                ('platform', models.CharField(choices=core.utils.platform_choices, max_length=255, verbose_name='Plateforme')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('profiles', models.PositiveIntegerField(default=0, verbose_name='N° Profile')),
                ('max_profile', models.PositiveIntegerField(default=5, verbose_name='Profile maximum')),
                ('type', models.CharField(choices=[('mutual', 'Mutualisé'), ('personal', 'Personnel'), ('trial', 'Essai')], default='mutual', max_length=100)),
                ('place', models.PositiveIntegerField(default=2, help_text="Nombre maximum d'abonnements pouvant être liés à ce compte", verbose_name='Places disponibles')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('month_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de mois')),
                ('card', models.CharField(blank=True, default='', max_length=255, verbose_name='Carte')),
                ('remaining_day', models.PositiveIntegerField(default=0, verbose_name='Jours restants')),
                ('status', models.CharField(choices=[('activate', 'Activé'), ('desactivate', 'Désactivé')], default='activate', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, verbose_name='Numéro')),
                ('code', models.CharField(max_length=128, verbose_name='Code')),
                ('place', models.PositiveIntegerField(choices=[(1, 'Place 1'), (2, 'Place 2')], default=1, help_text='Numéro de place (1 ou 2)', verbose_name='Place')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.account', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
