# Generated by Django 6.0.2 on 2026-03-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Numéro'),
        ),
    ]
