# Generated by Django 6.0.2 on 2026-03-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_profile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('mutual', 'Mutualisé'), ('personal', 'Personnel')], default='mutual', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('number', 'platform'), name='unique_account_number_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('email', 'platform'), name='unique_account_email_per_platform'),
        ),
    ]
