# Generated by Django 6.0.2 on 2026-08-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_account_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cvv',
        ),
    ]
