# Generated by Django 6.0.2 on 2026-08-10 17:20

import core.fields
from django.db import migrations


def encrypt_existing_credentials(apps, schema_editor):
    """Re-save Account rows so existing plain-text email/password become encrypted."""
    Account = apps.get_model('products', 'Account')
    for account in Account.objects.all():
        account.save(update_fields=['email', 'password'])


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_card_cvv'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_email_per_platform',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=core.fields.EncryptedCharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=core.fields.EncryptedCharField(max_length=255, verbose_name='Mot de passe'),
        ),
        migrations.RunPython(encrypt_existing_credentials, reverse_migration),
    ]
