# Generated by Django 6.0.2 on 2026-03-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_account_email_alter_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(max_length=128, verbose_name='Numéro'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('number', 'account'), name='unique_profile_number_per_account'),
        ),
    ]
