# Generated by Django 6.0.2 on 2026-05-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_profile_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-remaining_day'], 'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
    ]
