# Generated by Django 6.0.2 on 2026-07-14 08:55

from django.db import migrations, models
import products.models


def _drop_card_if_exists(schema_editor):
    """Drop the old card CharField column if it exists (vendor-aware)."""
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE products_account DROP COLUMN IF EXISTS card;")
    elif vendor == 'sqlite':
        # SQLite doesn't support DROP COLUMN in older versions, but Django 6.0
        # uses the new SQLite >=3.35 ALTER TABLE DROP COLUMN.
        # However, to be safe, we make the column nullable instead.
        try:
            # Try dropping the column (SQLite >=3.35)
            schema_editor.execute("ALTER TABLE products_account DROP COLUMN card;")
        except Exception:
            # If DROP fails, the column doesn't exist or SQLite too old — no-op
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_account_options'),
    ]

    operations = [
        # Create Card model
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', products.models.EncryptedCharField(max_length=255, verbose_name='Numéro')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la carte')),
                ('cvv', models.CharField(max_length=10, verbose_name='CVV')),
                ('telephone', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('expiration_date', models.DateField(verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cartes',
                'ordering': ['expiration_date', 'status'],
            },
        ),
        # Create AccountMarker model
        migrations.CreateModel(
            name='AccountMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('color', models.CharField(default='#ffffff', max_length=20, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Marqueur',
                'verbose_name_plural': 'Marqueurs',
            },
        ),
        # Remove old CharField card if it exists (vendor-aware)
        migrations.RunPython(
            code=lambda apps, schema_editor: _drop_card_if_exists(schema_editor),
            reverse_code=lambda apps, schema_editor: None,
        ),
        # Add card as FK (null=True so existing accounts don't break)
        migrations.AddField(
            model_name='account',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='products.card', verbose_name='Carte'),
        ),
        # Add markers M2M
        migrations.AddField(
            model_name='account',
            name='markers',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='products.accountmarker', verbose_name='Marqueurs'),
        ),
    ]
