# Generated by Django 6.0.2 on 2026-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_accountmarker_id_alter_card_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status', 'end_date'], name='account_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['platform', 'status'], name='account_platform_status_idx'),
        ),
    ]
